from django.urls import path
from .kakao import kakao_callback, kakao_login
from .views import (
    UserLogoutView, activity_view, add_friend, battle_arena, battle_view,
    check_in_attendance, complete_daily_quest, create_battle, dashboard, demo_battle, demo_level,
    dismiss_friend_notification, facilities_view, friends_view, login_view,
    onboarding_course, onboarding_entry, onboarding_group, onboarding_group_quest,
    onboarding_intro, onboarding_mode, onboarding_profile, onboarding_solo,
    outfit_shop, profile_view, ranking_view, record_workout, region_view,
    register_view, respond_friend_request, respond_party_invitation,
    sports_news_api, weather_api,
)

urlpatterns = [
    path("login/kakao/", kakao_login, name="kakao_login"),
    path("login/kakao/callback/", kakao_callback, name="kakao_callback"),
    path("", dashboard, name="dashboard"),
    path("register/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("onboarding/", onboarding_entry, name="onboarding"),
    path("onboarding/intro/", onboarding_intro, name="onboarding_intro"),
    path("onboarding/profile/", onboarding_profile, name="onboarding_profile"),
    path("onboarding/course/", onboarding_course, name="onboarding_course"),
    path("onboarding/mode/", onboarding_mode, name="onboarding_mode"),
    path("onboarding/solo/", onboarding_solo, name="onboarding_solo"),
    path("onboarding/group/", onboarding_group, name="onboarding_group"),
    path("onboarding/group/<int:party_id>/quest/", onboarding_group_quest, name="onboarding_group_quest"),
    path("profile/", profile_view, name="profile"),
    path("activity/", activity_view, name="activity"),
    path("record/", record_workout, name="record_workout"),
    path("attendance/check-in/", check_in_attendance, name="check_in_attendance"),
    path("quests/<str:quest_kind>/<int:quest_id>/complete/", complete_daily_quest, name="complete_daily_quest"),
    path("ranking/", ranking_view, name="ranking"),
    path("outfits/", outfit_shop, name="outfit_shop"),
    path("api/news/", sports_news_api, name="sports_news_api"),
    path("api/weather/", weather_api, name="weather_api"),
    path("friends/", friends_view, name="friends"),
    path("friends/add/", add_friend, name="add_friend"),
    path("friends/request/<int:request_id>/<str:action>/", respond_friend_request, name="respond_friend_request"),
    path("friends/dismiss/<int:request_id>/", dismiss_friend_notification, name="dismiss_friend_notification"),
    path("party/invitation/<int:invitation_id>/<str:action>/", respond_party_invitation, name="respond_party_invitation"),
    path("facilities/", facilities_view, name="facilities"),
    path("region/", region_view, name="region"),
    path("battle/", battle_view, name="battle"),
    path("battle/create/", create_battle, name="create_battle"),
    path("battle/<int:battle_id>/", battle_arena, name="battle_arena"),
    path("demo/level/", demo_level, name="demo_level"),
    path("demo/level/<int:target_level>/", demo_level, name="demo_level_target"),
    path("demo/battle/", demo_battle, name="demo_battle"),
]
