# Generated by Django 5.2.17 on 2026-09-12 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(choices=[('서울특별시', '서울특별시'), ('부산광역시', '부산광역시'), ('대구광역시', '대구광역시'), ('인천광역시', '인천광역시'), ('광주광역시', '광주광역시'), ('대전광역시', '대전광역시'), ('울산광역시', '울산광역시'), ('세종특별자치시', '세종특별자치시'), ('경기도', '경기도'), ('강원특별자치도', '강원특별자치도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전북특별자치도', '전북특별자치도'), ('전라남도', '전라남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('제주특별자치도', '제주특별자치도')], max_length=30)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CardBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('PARTY', '파티원 배틀'), ('REGION', '지역 카드 배틀')], max_length=10)),
                ('opponent_name', models.CharField(max_length=80)),
                ('opponent_level', models.PositiveIntegerField(default=1)),
                ('region_name', models.CharField(blank=True, max_length=30)),
                ('reward', models.CharField(choices=[('NONE', '보상 없음'), ('COFFEE', '커피 사기 ☕'), ('MEAL', '밥 사기 🍚'), ('CHICKEN', '치킨 사기 🍗'), ('CAFE', '카페 디저트 사기 🍰'), ('MOVIE', '영화 보여주기 🎬'), ('CUSTOM', '직접 입력')], default='NONE', max_length=10)),
                ('custom_reward', models.CharField(blank=True, max_length=100)),
                ('challenger_power', models.PositiveIntegerField(default=0)),
                ('opponent_power', models.PositiveIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='러닝 새싹', max_length=30)),
                ('frame', models.CharField(default='새싹', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal_km', models.PositiveIntegerField(default=100)),
                ('members', models.ManyToManyField(related_name='parties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('서울특별시', '서울특별시'), ('부산광역시', '부산광역시'), ('대구광역시', '대구광역시'), ('인천광역시', '인천광역시'), ('광주광역시', '광주광역시'), ('대전광역시', '대전광역시'), ('울산광역시', '울산광역시'), ('세종특별자치시', '세종특별자치시'), ('경기도', '경기도'), ('강원특별자치도', '강원특별자치도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전북특별자치도', '전북특별자치도'), ('전라남도', '전라남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('제주특별자치도', '제주특별자치도')], default='서울특별시', max_length=20)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('N', '선택 안 함')], default='N', max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('skeletal_muscle_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('avatar_preference', models.CharField(choices=[('AUTO', '자동 추천'), ('SLIM', '날씬형'), ('BALANCED', '균형형'), ('SOFT', '여유형'), ('MUSCULAR', '근육형')], default='AUTO', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('러닝', '러닝'), ('걷기', '걷기'), ('헬스', '헬스'), ('자전거', '자전거'), ('수영', '수영'), ('배드민턴', '배드민턴'), ('기타', '기타')], max_length=10)),
                ('minutes', models.PositiveIntegerField()),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('with_party', models.BooleanField(default=False)),
                ('earned_xp', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
