# Generated by Django 5.2.17 on 2026-09-15 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_kakaoaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='party',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='party',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='disability_status',
            field=models.CharField(choices=[('UNSET', '응답 안 함'), ('NONE', '비장애인'), ('DISABLED', '장애인')], default='UNSET', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_activity_mode',
            field=models.CharField(choices=[('UNSET', '미선택'), ('SOLO', '솔로'), ('GROUP', '그룹')], default='UNSET', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheelchair_usage',
            field=models.CharField(choices=[('UNSET', '응답 안 함'), ('NO', '이용하지 않음'), ('OPTIONAL', '상황에 따라 이용'), ('REQUIRED', '필수')], default='UNSET', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_preference',
            field=models.CharField(choices=[('AUTO', '자동 추천'), ('SLIM', '날씬형'), ('BALANCED', '균형형'), ('SOFT', '통통형'), ('ACTIVE', '활동형'), ('MUSCULAR', '강한 운동형')], default='AUTO', max_length=10),
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.PositiveSmallIntegerField(default=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('capacity', models.PositiveSmallIntegerField(choices=[(2, '1대1'), (4, '2대2')])),
                ('penalty', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('RECRUITING', '모집'), ('ACTIVE', '진행'), ('FINISHED', '종료'), ('CANCELLED', '취소')], default='RECRUITING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battle_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='battle_rooms', through='fitness.BattleParticipant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fitness.battleroom'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SOLO', '데일리 퀘스트'), ('GROUP', '그룹 퀘스트')], max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('requires_photo', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', '준비'), ('ACTIVE', '진행'), ('FINISHED', '종료')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_missions', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='fitness.party')),
            ],
        ),
        migrations.AddField(
            model_name='battleroom',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='battle_room', to='fitness.mission'),
        ),
        migrations.CreateModel(
            name='MissionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='fitness.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='participants',
            field=models.ManyToManyField(related_name='missions', through='fitness.MissionParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProofSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='proofs/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', '검토 대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='fitness.missionparticipant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='battleparticipant',
            constraint=models.UniqueConstraint(fields=('battle', 'user'), name='unique_battle_participant'),
        ),
        migrations.AddConstraint(
            model_name='missionparticipant',
            constraint=models.UniqueConstraint(fields=('mission', 'user'), name='unique_mission_participant'),
        ),
    ]
