# Generated by Django 5.2.17 on 2026-09-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_party_challenge_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeaward',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='quest_proofs/'),
        ),
        migrations.AddField(
            model_name='workoutrecord',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_proofs/'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mode',
            field=models.CharField(choices=[('SOLO', '데일리 미션'), ('GROUP', '그룹 미션')], max_length=8),
        ),
        migrations.AlterField(
            model_name='outfitpurchase',
            name='outfit',
            field=models.CharField(choices=[('BAND', '스포티 네온 헤어밴드'), ('GLASS', '사이버 네온 선글라스'), ('HEADSET', '사이버 게이밍 헤드셋'), ('MASK', '사이버 닌자 마스크'), ('BELT', '골드 챔피언 벨트'), ('CAP', '운동 모자'), ('MEDAL', '골드 빅토리 목걸이'), ('GLOVES', '파이어 복싱 글러브'), ('SPORT', '스포츠 유니폼'), ('CLOAK', '다크 히어로 망토'), ('SWORD', '네온 빔세이버'), ('CROWN', '챔피언 왕관'), ('WING', '사이버 홀로그램 윙'), ('DRAGON', '미니 파이어 펫'), ('AURA', '불꽃 버닝 파이어 오라'), ('VICTORY', '골드 빅토리 트로피')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='equipped_outfit',
            field=models.CharField(blank=True, default='NONE', max_length=120),
        ),
    ]
