# Generated by Django 5.2.17 on 2026-09-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_merge_gwangju_jeonnam_region'),
        ('fitness', '0013_friendrequest_partyinvitation'),
    ]

    operations = [
    ]
