# Generated by Django 5.2.17 on 2026-09-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_friendrequest_partyinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='sender_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partyinvitation',
            name='inviter_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
