# Generated by Django 5.2.17 on 2026-09-18 03:13

import fitness.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_merge_20260918_1144'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partyinvitation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badgeaward',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='quest_proofs/', validators=[fitness.validators.validate_proof_image]),
        ),
        migrations.AlterField(
            model_name='workoutrecord',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_proofs/', validators=[fitness.validators.validate_proof_image]),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='friend_request_not_self'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('from_user', 'to_user'), name='unique_pending_friend_request'),
        ),
        migrations.AddConstraint(
            model_name='partyinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('party', 'invitee'), name='unique_pending_party_invitation'),
        ),
    ]
