# Generated by Django 5.2.17 on 2026-09-18 07:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_friendrequest_sender_viewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldailyquest',
            name='current_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personaldailyquest',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personaldailyquest',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='fitness.facility'),
        ),
        migrations.AddField(
            model_name='personaldailyquest',
            name='mission_category',
            field=models.CharField(choices=[('ATTENDANCE', '출석 체크'), ('WORKOUT', '운동 수행'), ('FACILITY', '주변 시설'), ('CUMULATIVE', '주간 누적')], default='WORKOUT', max_length=20),
        ),
        migrations.AddField(
            model_name='personaldailyquest',
            name='period_type',
            field=models.CharField(choices=[('DAILY', '일일'), ('WEEKLY', '주간')], default='DAILY', max_length=10),
        ),
        migrations.AddField(
            model_name='personaldailyquest',
            name='reward_points',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='personaldailyquest',
            name='target_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaldailyquest',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldailyquest',
            name='source',
            field=models.CharField(choices=[('DIRECT', '직접 입력'), ('AI', 'AI 추천'), ('SYSTEM', '시스템')], default='DIRECT', max_length=8),
        ),
        migrations.AlterField(
            model_name='personaldailyquest',
            name='target_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personaldailyquest',
            name='workout_type',
            field=models.CharField(blank=True, choices=[('러닝', '러닝'), ('걷기', '산책'), ('헬스', '헬스'), ('자전거', '자전거'), ('수영', '수영'), ('배드민턴', '배드민턴'), ('등산', '등산'), ('축구', '축구'), ('농구', '농구'), ('요가', '요가'), ('기타', '기타')], default='기타', max_length=10),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_attendance')],
            },
        ),
    ]
