# Generated by Django 5.2.17 on 2026-09-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_friendrequest_sender_viewed_and_more'),
        ('fitness', '0015_friendrequest_responded_at_and_more'),
    ]

    operations = [
    ]
