# Generated by Django 5.2.17 on 2026-09-18 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_personaldailyquest_current_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='current_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_quests', to='fitness.facility'),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='mission_category',
            field=models.CharField(choices=[('ATTENDANCE', '출석 체크'), ('WORKOUT', '협동 운동'), ('FACILITY', '주변 시설'), ('CUMULATIVE', '주간 누적')], default='WORKOUT', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='period_type',
            field=models.CharField(choices=[('DAILY', '일일'), ('WEEKLY', '주간')], default='DAILY', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='reward_points',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='source',
            field=models.CharField(choices=[('DIRECT', '직접 입력'), ('AI', 'AI 추천'), ('SYSTEM', '시스템')], default='AI', max_length=8),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='target_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_daily_quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='target_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='workout_type',
            field=models.CharField(blank=True, choices=[('러닝', '러닝'), ('걷기', '산책'), ('헬스', '헬스'), ('자전거', '자전거'), ('수영', '수영'), ('배드민턴', '배드민턴'), ('등산', '등산'), ('축구', '축구'), ('농구', '농구'), ('요가', '요가'), ('기타', '기타')], default='기타', max_length=10),
        ),
    ]
