# Generated by Django 5.2.17 on 2026-09-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_dailyquest_current_progress_dailyquest_description_and_more'),
        ('fitness', '0016_merge_20260918_1453'),
    ]

    operations = [
    ]
