# Generated by Django 5.2.17 on 2026-09-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_pokenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='challenge_end_time',
            field=models.TimeField(blank=True, help_text='내기 마감 시각 (타이머)', null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='target_timer_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='파티 목표 운동 시간(분)'),
        ),
    ]
