# Generated by Django 5.2.17 on 2026-09-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_party_challenge_end_time_party_target_timer_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='workout_type',
            field=models.CharField(blank=True, default='러닝', help_text='파티 목표 운동 종류', max_length=20),
        ),
    ]
