# Generated by Django 5.2.17 on 2026-09-22 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0019_party_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='source_record_id',
            field=models.CharField(blank=True, help_text='원본 시설 식별자 또는 정규화된 시설 정보의 SHA-256 값', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='DataSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('RUNNING', '실행 중'), ('SUCCESS', '성공'), ('FAILED', '실패'), ('SKIPPED_NO_CHANGE', '변경 없음')], default='PENDING', max_length=20)),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'RUNNING')), fields=('source_name',), name='unique_running_facility_sync')],
            },
        ),
    ]
