# Generated by Django 5.2.17 on 2026-09-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_merge_20260921_0949'),
        ('fitness', '0019_party_workout_type'),
    ]

    operations = [
    ]
