# Generated by Django 5.2.17 on 2026-09-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0020_merge_20260922_1100'),
        ('fitness', '0023_align_facility_source_ids'),
    ]

    operations = [
    ]
